iserter.lo: /Users/iserter/PhpstormProjects/iserter/ext/iserter.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/iserter/PhpstormProjects/iserter/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/iserter/PhpstormProjects/iserter/ext/iserter.c -o iserter.lo 
kernel/main.lo: /Users/iserter/PhpstormProjects/iserter/ext/kernel/main.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/iserter/PhpstormProjects/iserter/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/iserter/PhpstormProjects/iserter/ext/kernel/main.c -o kernel/main.lo 
kernel/memory.lo: /Users/iserter/PhpstormProjects/iserter/ext/kernel/memory.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/iserter/PhpstormProjects/iserter/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/iserter/PhpstormProjects/iserter/ext/kernel/memory.c -o kernel/memory.lo 
kernel/exception.lo: /Users/iserter/PhpstormProjects/iserter/ext/kernel/exception.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/iserter/PhpstormProjects/iserter/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/iserter/PhpstormProjects/iserter/ext/kernel/exception.c -o kernel/exception.lo 
kernel/hash.lo: /Users/iserter/PhpstormProjects/iserter/ext/kernel/hash.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/iserter/PhpstormProjects/iserter/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/iserter/PhpstormProjects/iserter/ext/kernel/hash.c -o kernel/hash.lo 
kernel/debug.lo: /Users/iserter/PhpstormProjects/iserter/ext/kernel/debug.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/iserter/PhpstormProjects/iserter/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/iserter/PhpstormProjects/iserter/ext/kernel/debug.c -o kernel/debug.lo 
kernel/backtrace.lo: /Users/iserter/PhpstormProjects/iserter/ext/kernel/backtrace.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/iserter/PhpstormProjects/iserter/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/iserter/PhpstormProjects/iserter/ext/kernel/backtrace.c -o kernel/backtrace.lo 
kernel/object.lo: /Users/iserter/PhpstormProjects/iserter/ext/kernel/object.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/iserter/PhpstormProjects/iserter/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/iserter/PhpstormProjects/iserter/ext/kernel/object.c -o kernel/object.lo 
kernel/array.lo: /Users/iserter/PhpstormProjects/iserter/ext/kernel/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/iserter/PhpstormProjects/iserter/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/iserter/PhpstormProjects/iserter/ext/kernel/array.c -o kernel/array.lo 
kernel/extended/array.lo: /Users/iserter/PhpstormProjects/iserter/ext/kernel/extended/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/iserter/PhpstormProjects/iserter/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/iserter/PhpstormProjects/iserter/ext/kernel/extended/array.c -o kernel/extended/array.lo 
kernel/string.lo: /Users/iserter/PhpstormProjects/iserter/ext/kernel/string.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/iserter/PhpstormProjects/iserter/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/iserter/PhpstormProjects/iserter/ext/kernel/string.c -o kernel/string.lo 
kernel/fcall.lo: /Users/iserter/PhpstormProjects/iserter/ext/kernel/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/iserter/PhpstormProjects/iserter/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/iserter/PhpstormProjects/iserter/ext/kernel/fcall.c -o kernel/fcall.lo 
kernel/extended/fcall.lo: /Users/iserter/PhpstormProjects/iserter/ext/kernel/extended/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/iserter/PhpstormProjects/iserter/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/iserter/PhpstormProjects/iserter/ext/kernel/extended/fcall.c -o kernel/extended/fcall.lo 
kernel/require.lo: /Users/iserter/PhpstormProjects/iserter/ext/kernel/require.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/iserter/PhpstormProjects/iserter/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/iserter/PhpstormProjects/iserter/ext/kernel/require.c -o kernel/require.lo 
kernel/file.lo: /Users/iserter/PhpstormProjects/iserter/ext/kernel/file.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/iserter/PhpstormProjects/iserter/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/iserter/PhpstormProjects/iserter/ext/kernel/file.c -o kernel/file.lo 
kernel/operators.lo: /Users/iserter/PhpstormProjects/iserter/ext/kernel/operators.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/iserter/PhpstormProjects/iserter/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/iserter/PhpstormProjects/iserter/ext/kernel/operators.c -o kernel/operators.lo 
kernel/math.lo: /Users/iserter/PhpstormProjects/iserter/ext/kernel/math.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/iserter/PhpstormProjects/iserter/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/iserter/PhpstormProjects/iserter/ext/kernel/math.c -o kernel/math.lo 
kernel/concat.lo: /Users/iserter/PhpstormProjects/iserter/ext/kernel/concat.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/iserter/PhpstormProjects/iserter/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/iserter/PhpstormProjects/iserter/ext/kernel/concat.c -o kernel/concat.lo 
kernel/variables.lo: /Users/iserter/PhpstormProjects/iserter/ext/kernel/variables.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/iserter/PhpstormProjects/iserter/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/iserter/PhpstormProjects/iserter/ext/kernel/variables.c -o kernel/variables.lo 
kernel/filter.lo: /Users/iserter/PhpstormProjects/iserter/ext/kernel/filter.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/iserter/PhpstormProjects/iserter/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/iserter/PhpstormProjects/iserter/ext/kernel/filter.c -o kernel/filter.lo 
kernel/iterator.lo: /Users/iserter/PhpstormProjects/iserter/ext/kernel/iterator.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/iserter/PhpstormProjects/iserter/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/iserter/PhpstormProjects/iserter/ext/kernel/iterator.c -o kernel/iterator.lo 
kernel/time.lo: /Users/iserter/PhpstormProjects/iserter/ext/kernel/time.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/iserter/PhpstormProjects/iserter/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/iserter/PhpstormProjects/iserter/ext/kernel/time.c -o kernel/time.lo 
kernel/exit.lo: /Users/iserter/PhpstormProjects/iserter/ext/kernel/exit.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/iserter/PhpstormProjects/iserter/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/iserter/PhpstormProjects/iserter/ext/kernel/exit.c -o kernel/exit.lo 
iserter/test.lo: /Users/iserter/PhpstormProjects/iserter/ext/iserter/test.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/iserter/PhpstormProjects/iserter/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/iserter/PhpstormProjects/iserter/ext/iserter/test.zep.c -o iserter/test.lo 
iserter/utils/collection.lo: /Users/iserter/PhpstormProjects/iserter/ext/iserter/utils/collection.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/iserter/PhpstormProjects/iserter/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/iserter/PhpstormProjects/iserter/ext/iserter/utils/collection.zep.c -o iserter/utils/collection.lo 
$(phplibdir)/iserter.la: ./iserter.la
	$(LIBTOOL) --mode=install cp ./iserter.la $(phplibdir)

./iserter.la: $(shared_objects_iserter) $(ISERTER_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_iserter) $(ISERTER_SHARED_LIBADD)

